on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install -y cppcheck clang-tidy  clang-tools  python3  python3-pip  make libgtest-dev   lcov  libc6-dbg
      - run: pip install cpplint 
      - run: make check
      - run: make format

  build_run_fsanitizer:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
    - run: make build_fsanitizer
    - run: make test

  build_run_valgrind:
    runs-on: ubuntu-latest
    needs: [build_run_fsanitizer]
    steps:
      - run: make rm_build
      - run: make build
      - run: make test_valgrind
  
  test_coverage:
    runs-on: ubuntu-latest
    needs: [build_run_valgrind]
    steps:
      - run: make test
      - run: make test_coverage
      