on: push

jobs:
  Build_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install env
        run: sudo apt update && sudo apt install cppcheck clang-tidy  clang-tools  python3  python3-pip  make libgtest-dev lcov  libc6-dbg && pip install cpplint 

      - name: check
        run: make check && make format

  

      - name: build_run_valgrind
        run: make build && make test_valgrind

      - name: test_coverage
        run: make test && make test_coverage
      