on: push

jobs:
  Build_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install env
        run: sudo apt update && sudo apt install cppcheck clang-tidy  clang-tools  python3  python3-pip  make libgtest-dev lcov libc6-dbg valgrind tree && pip install cpplint 

      - name: check
        run: make check && make format

      - name: build_run_fsanitizer
        run: make build_fsanitizer && make test

      - name: build_run_valgrind
        run: make rm_build && make build && make test_valgrind

      - name: test_coverage
        run: make rm_build && make build && make test && tree && make test_coverage