on: push

jobs:
  install_all:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install -y cppcheck  
      - run: sudo apt install -y clang-tidy 
      - run: sudo apt install -y clang-tools 
      - run: sudo apt install -y python3  
      - run: sudo apt install -y python3-pip  
      - run: sudo apt install -y cmake  
      - run: sudo apt install -y libgtest-dev 
      - run: sudo apt install -y lcov 
      - run: pip install cpplint
      - run: sudo apt install -y libc6-dbg 

  check:
    runs-on: ubuntu-latest
    needs: [install_all]
    steps:
      - run: make check
      - run: make format

  build_run_fsanitizer:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
    - run: make build_fsanitizer
    - run: make test

  build_run_valgrind:
    runs-on: ubuntu-latest
    needs: [build_run_fsanitizer]
    steps:
      - run: make rm_build
      - run: make build
      - run: make test_valgrind
  
  test_coverage:
    runs-on: ubuntu-latest
    needs: [build_run_valgrind]
    steps:
      - run: make test
      - run: make test_coverage
      